substitutions:
  name: aircon_mitsubishi
  friendly_name: Mitsubishi AC

esphome:
  name: $name
  friendly_name: $friendly_name

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO43
  rx_pin: GPIO44

# Enable logging
logger:
  level: INFO

api:
  encryption:
    key: !secret key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid_tossa
  password: !secret wifi_password_tossa
  fast_connect: true  # disables scan (not needed for a single network)

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$name"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80


# External component reference
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# Climate entity configuration
climate:
  - platform: cn105
    id: hp
    name: "My Heat Pump"
    update_interval: 2s # update interval can be adjusted after a first run and logs monitoring

sensor:
  - platform: uptime
    name: Uptime
